title: Rohit Vernekar
description: Data Engineer and Machine Learning Specialist
baseurl: ""
# url: https://piazzai.github.io

# theme: hacked-jekyll
remote_theme: piazzai/hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  