title: Rohit Vernekar
description: Jekyll microtheme that looks like JSON
baseurl: ""
# url: https://piazzai.github.io

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  